name: aprilworkflow
on: push
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print "hello world"
        run: echo "hello world"  
      - name: install tree
        run: apt install tree -y   

  second-job:
    runs-on: windows-latest
    steps: 
      - name: print "hello world"
        run: echo "hello world"  
      - name: install tree
        run: apt install tree -y            
