name: terraform s3 workflow
on: 
  workflow_dispatch:
    inputs:
      action:
        required: true
        default: plan
        type: choice
        options: 
          - init
          - plan
          - apply
          - all 
jobs:
  terraform-checks:
    uses: ./.github/workflows/terraform-validate.yml 
  terraform:
    needs: terraform-checks
    runs-on: ubuntu-latest
    steps: 
      - name: clone the repository
        uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0              
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1 
      - name: initilize terraform
        if: ${{ inputs.action == 'init' || inputs.action == 'all' }}
        run: terraform init
      - name: plan terraform
        if: ${{ inputs.action == 'plan' || inputs.action == 'all' }}          
        run: |
          terraform init
          terraform plan
      
      - name: terraform apply 
        if: ${{ inputs.action == 'apply' || inputs.action == 'all' }}        
        run: |
          terraform init
          terraform apply -auto-approve
        
