name: terraform-workflow
on: 

  workflow_dispatch:    

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: clone the repository
        uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0              
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1 
      - name: initilize terraform
        run: terraform init
      - name: plan terraform          
        run: terraform plan
      - name: terraform apply   
        run: terraform apply -auto-approve